# Production overrides for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  backend:
    environment:
      - ENVIRONMENT=production
      - CORS_ORIGINS=https://itaboo.store,https://www.itaboo.store
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    environment:
      - VITE_API_URL=https://itaboo.store/api
      - NODE_ENV=production
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
